### ISSUE TITLE
Quick chat close button issue

### ISSUE THREAD

**Issue by forrana** [diglabby/diglab_landing_page#23]
It was hard for me to find close button from quick chat there is to points

1) Intuitively I was trying to find it in the upper right corner
2) Probably it's just my display problem, but it's hard to find cross on that button with current colors 
http://www.clipular.com/c/5657634305998848.png?k=tzI6xA0DuhPQ76p8LAucfBI_uGY
That's why it was hard for me to understand what it button stay for here

**Comment by falanster** [comment]
прывет, 
так, нас таксама запарыла што яна атдкрытая. калі мы знойдзем параметр каб зрабіць яе закрытаю заўсёды па ззмоўнчанні будзе гут.

**Comment by falanster** [comment]
Робім дабротны самапал тут:
https://trello.com/b/4zf2M29T/digital-lab-chat-slack
